// Generated by CoffeeScript 1.9.3
(function() {
  var anims, app, colors, express, http, io, nunjucks, range;

  express = require('express');

  app = express();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  nunjucks = require('nunjucks');

  range = require('lodash/utility/range');

  colors = ['000000', 'ffffff', 'ff0000', '00ff00', '0000ff', '00ffff', 'ffff00'];

  anims = {
    'fg': range(5),
    'bg': range(5),
    'custom': range(5),
    'color': colors
  };

  app.set('port', process.env.PORT || 5000);

  app.use(express["static"](__dirname + '/public'));

  nunjucks.configure('templates', {
    autoescape: true,
    express: app
  });

  app.get('/', function(req, res) {
    return res.render('index.html', {
      anims: anims
    });
  });

  app.get('/ubik', function(req, res) {
    return res.render('ubik.html');
  });

  io.on('connection', function(socket) {
    console.log('connection');
    socket.on('anim request', function(msg) {
      console.log(msg);
      return io.emit('anim response', msg);
    });
    return socket.on('disconnect', function() {
      return console.log('disconnected');
    });
  });

  http.listen(app.get('port'), function() {
    return console.log('listening on *:' + app.get('port'));
  });

}).call(this);
